version: "3.9"

services:
    db_server:
        build: 
            context: .
            dockerfile: Dockerfile_pg
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: pro
            POSTGRES_USER: postgres
            POSTGRES_DB: amaTraiteur
    php_server:
        build:
            context: .
            dockerfile: Dockerfile_php
        image: php_server:latest
        ports:
            - "8080:80"
        volumes:
            - ./www/:/var/www/html/
        environment:
            - DB_USER=postgres
            - DB_PASSWORD=pro